### ISSUE TITLE
Add support for Microsoft accounts

### ISSUE THREAD

**Issue by Delthas** [Delthas/JavaSkype#24]
Some users would like to use this library with Microsoft accounts (#23), maybe add that in the future.

**Comment by MrPowerGamerBR** [comment]
There was a code on how to login in a Microsoft account at https://github.com/samczsun/Skype4J/issues/128 , but the message was deleted (and the user account doesn't exist anymore)

Maybe @Manevolent still has his fix for Skype4J?

**Comment by Delthas** [comment]
I think I know how to do this, the process is detailed here: https://github.com/msndevs/protocol-docs/wiki/Authentication#microsoft-accounts

**Comment by Manevolent** [comment]
I do!

https://gist.github.com/Manevolent/1c6bc379c10c1e50358e8f2e2356fef7

That's what I've been using since the mentioned ticket, I made some minor changes to the original poster's source but this has been working fine for me.

**Comment by klingan** [comment]
@Manevolent since we are 4 months later, were you able to resolve your auth issues? A pull request would still come in handy :hankey:

**Comment by simk0024** [comment]
I think this should be put in higher priority, as all skype account are forced to link with Microsoft now...

**Comment by ruha9005** [comment]
May be it can help:
https://skpy.t.allofti.me/protocol/login.html

**Comment by ItsGravix** [comment]
@Manevolent I get this:
`org.json.JSONException: JSONObject["wst:RequestedSecurityToken"] not found.`

**Comment by Erezbiox1** [comment]
Exception in thread "main" java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: 1

**Comment by Erezbiox1** [comment]
Can anyone please help me out on this?

**Comment by Erezbiox1** [comment]
Simply removing the line from the gist seems to work...
weird.
the line is "this.cookies.put(setCookie[0], setCookie[1]);"

**Comment by metasonic** [comment]
@Erezbiox1 any chance you got a fork of this with the fix applied for logging in with email and password or provide a short guide on how to get this working? Thank you!

**Comment by Delthas** [comment]
Hello, I will look into this this week. Sorry for the long delay. To be honest I wasn't sure if anyone needed this at all.

**Comment by Erezbiox1** [comment]
@metasonic Yes, [here's the gist](https://gist.github.com/Erezbiox1/68c1b453269ef5b24bac25714414022e), 
and here's the required libraries: 
![image](https://user-images.githubusercontent.com/22329115/32545195-94ce5f7a-c483-11e7-8a48-6bd044a4447a.png)
Do note, this only works with Skype4J

**Comment by metasonic** [comment]
@Erezbiox1Thanks a lot for that, integrated it locally with Skype4J, tested it and it works, but having issues using the packaged Skype4J in another project. Would you guys recommend moving forward like this or using java spring and the new MicrosoftBotFramework?

**Comment by metasonic** [comment]
@Delthas the framework you buit is the perfect plug and play not stress that you need for Skype, so, I for one love it and would like to see it grow

**Comment by Delthas** [comment]
Hello. Good news! I have added support for Microsoft accounts. There are no API changes besides the fact logging with a Microsoft account (e.g. foo.bqr@hotmail.com) should work.
Please update your version to 1.0.22 (I've copied the ```<dependency>``` block below). Open a new issue for any problem you may have, but do send me debug logs when opening an issue (simply call [setDebug](http://static.javadoc.io/fr.delthas/javaskype/1.0.20/fr/delthas/skype/Skype.html#setDebug-java.nio.file.Path-) to create a debug file).
```
    <dependency>       
           <groupId>fr.delthas</groupId>
           <artifactId>javaskype</artifactId>
           <version>1.0.22</version>
    </dependency>
```

**Comment by indeterminatus** [comment]
@Delthas thanks for tackling this issue in such a speedy fashion now :). There still seems to be a problem when using a Skype account that has been linked to a Microsoft account (as is the case for me). I can provide two debug logs (one for Skype login, one for Microsoft Account login) and would be quite willing to help resolve this -- kindly contact me via e-mail.

**Comment by metasonic** [comment]
@Delthas thanks a lot for this!

**Comment by metasonic** [comment]
After doing the following steps skype.connect(); remains stuck 
**Steps:**
1. create a new skype object
2. initialize connection (skype.connect();)
3. get the groups you are into (skype.getGroups(); )
4. disconnect
*Notice that after doing this a few times the script will remain stuck at the skype.connect part
PS. sometimes it gives the following error:
`Exception in thread "Skype-Receiver-Thread" java.lang.IllegalArgumentException
	at fr.delthas.skype.NotifConnector.parseEntity(NotifConnector.java:792)
	at fr.delthas.skype.NotifConnector.updateThread(NotifConnector.java:738)
	at fr.delthas.skype.NotifConnector.processPacket(NotifConnector.java:254)
	at fr.delthas.skype.NotifConnector.lambda$new$0(NotifConnector.java:73)
	at java.lang.Thread.run(Thread.java:745)`

**Debug logs**
[https://www.dropbox.com/s/5mql7cyxs9na9tj/debug3.txt?dl=0](url) 
[https://www.dropbox.com/s/e6uzyrjos7gfefl/debug2.txt?dl=1](url)
