### ISSUE TITLE
"Skype-Receiver-Thread" java.lang.IllegalArgumentException - on Skype#connect

### ISSUE THREAD

**Issue by sponges** [Delthas/JavaSkype#3]
```
Exception in thread "Skype-Receiver-Thread" java.lang.IllegalArgumentException
    at fr.delthas.skype.NotifConnector.parseEntity(NotifConnector.java:597)
    at fr.delthas.skype.NotifConnector.updateThread(NotifConnector.java:559)
    at fr.delthas.skype.NotifConnector.processPacket(NotifConnector.java:152)
    at fr.delthas.skype.NotifConnector.lambda$connect$2(NotifConnector.java:405)
    at fr.delthas.skype.NotifConnector$$Lambda$2/141289226.run(Unknown Source)
    at java.lang.Thread.run(Thread.java:745)
```

``` java
Skype skype = new Skype(USERNAME, PASSWORD);
try {
    skype.connect();
} catch (IOException | InterruptedException e) {
    e.printStackTrace();
}

skype.setErrorListener(Exception::printStackTrace);

skype.addGroupMessageListener(((group, user, message) -> {
    if (message.equalsIgnoreCase("hi")) {
        group.sendMessage("hi, " + user.getUsername());
    } else if (message.equalsIgnoreCase("stop")) {
        running = false;
    }
}));
```

I used IntelliJ's debugger to find where the issue was happening:
![screenshot](https://im.not.ovh/sySBsLkH2ZUbsTr.png)

**Comment by sponges** [comment]
Seems to only happen on my account.. username: ronniepickeringscar - password is very short.
Not a microsoft account either, tried the account on another person who had the same error, yet his account works fine.

**Comment by itsGhost** [comment]
[19/07/2016 01:43:24] Sponges: hey
[19/07/2016 01:43:33] Sponges: do you have ronniepickeringscar as a contact
[19/07/2016 01:44:10 | Edited 01:44:16] Reece: think so
[19/07/2016 01:44:18] Sponges: ok cus it got suspended
[19/07/2016 01:44:20] Reece: ye
[19/07/2016 01:44:22] Reece: kek
[19/07/2016 01:44:29] Reece: within this last hour?


[19/07/2016 01:39:36] Sponges: {"status":{"code":40330,"text":"User is blocked. Account takeover (ATO)."}}
[19/07/2016 01:39:39] Sponges: interesting
[19/07/2016 01:39:44] Sponges: did they break ronniepickeringscar..

**Comment by Delthas** [comment]
I have added a lot of debug in order to find what's causing the issue. Please download and run the latest version (1.0.12) of the library with debug enabled (add `Skype.setDebug(path)` before `skype.connect()`, a log file will be created at path `path`) and send me the log file. That is, if the bug still occurs in 1.0.12.
Thanks.

**Comment by Delthas** [comment]
Closed for lack of logs. Please reopen this issue if you have logs to send.
