### ISSUE TITLE
fr.delthas.skype.ParseException: Error message received: 911 2 CON 23 (#2)

### ISSUE THREAD

**Issue by awkaw** [Delthas/JavaSkype#30]
Error 911 2 CON 23 is repeated. Not always. Sometimes. OS Debian 8.
Windows 7 OS - all good!

`Mar 22, 2017 12:28:52 PM fr.delthas.skype.NotifConnector readPacket
SEVERE:
fr.delthas.skype.ParseException: Error message received:
911 2 CON 23

Authentication failed
at fr.delthas.skype.NotifConnector.readPacket(NotifConnector.java:484)
at fr.delthas.skype.NotifConnector.lambda$connect$4(NotifConnector.java:512)
at java.lang.Thread.run(Thread.java:745)

Mar 22, 2017 12:28:52 PM fr.delthas.skype.NotifConnector lambda$connect$4
SEVERE: Error while reading packet
fr.delthas.skype.ParseException: Error message received:
911 2 CON 23

Authentication failed
at fr.delthas.skype.NotifConnector.readPacket(NotifConnector.java:484)
at fr.delthas.skype.NotifConnector.lambda$connect$4(NotifConnector.java:512)
at java.lang.Thread.run(Thread.java:745)

Mar 22, 2017 12:28:52 PM fr.delthas.skype.Skype error
SEVERE: Error thrown
fr.delthas.skype.ParseException: Error message received:
911 2 CON 23

Authentication failed
at fr.delthas.skype.NotifConnector.readPacket(NotifConnector.java:484)
at fr.delthas.skype.NotifConnector.lambda$connect$4(NotifConnector.java:512)
at java.lang.Thread.run(Thread.java:745)

Mar 22, 2017 12:28:52 PM fr.delthas.skype.Skype error
SEVERE: No error listener set!!!`

**Comment by Delthas** [comment]
Hello,  
Please send me the full debug file so that I can understand the cause of the error.
Just call `Skype.setDebug(Paths.get("/path/to/log/file.log"));` before `skype.connect();` and send me the full log file generated by skype.

Thanks.

**Comment by awkaw** [comment]
UIC and USERNAME changed :)

`Mar 24, 2017 10:52:14 AM fr.delthas.skype.Skype connect
FINE: Connecting to Skype
Mar 24, 2017 10:52:14 AM fr.delthas.skype.Skype reset
FINEST: Resetting the Skype object
Mar 24, 2017 10:52:14 AM fr.delthas.skype.NotifConnector generateEPID
FINEST: Generated EPID: ff3134d0-c184-b800-3b64-056dd4f8cdd9
Mar 24, 2017 10:52:14 AM fr.delthas.skype.WebConnector start
FINER: Starting web connector
Mar 24, 2017 10:52:14 AM fr.delthas.skype.WebConnector generateTokens
FINEST: Getting skype token
Mar 24, 2017 10:52:14 AM fr.delthas.skype.WebConnector sendRequest
FINEST: Sending POST request at https://api.skype.com/login/skypetoken
Mar 24, 2017 10:52:14 AM fr.delthas.skype.WebConnector sendRequest
FINE: No token sent for the request at: https://api.skype.com/login/skypetoken
Mar 24, 2017 10:52:17 AM fr.delthas.skype.NotifConnector connect
FINER: Starting notification connector
Mar 24, 2017 10:52:17 AM fr.delthas.skype.NotifConnector connectTo
FINEST: Connecting to hostname: s.gateway.messenger.live.com port: 443
Mar 24, 2017 10:52:18 AM fr.delthas.skype.NotifConnector sendPacket
FINEST: Sent packet: CNT 1 CON 106

<connect><ver>2</ver><agent><os>.</os><osVer>.</osVer><proc>.</proc><lcid>en-us</lcid></agent></connect>
Mar 24, 2017 10:52:18 AM fr.delthas.skype.NotifConnector connect
FINEST: Ping interval: 120000ms
Mar 24, 2017 10:52:18 AM fr.delthas.skype.NotifConnector connect
FINER: Waiting for connection
Mar 24, 2017 10:52:18 AM fr.delthas.skype.NotifConnector processPacket
FINER: Received packet CNT CON
Mar 24, 2017 10:52:18 AM fr.delthas.skype.NotifConnector processPacket
FINEST: Recieved packet body: <connect-response><ver>2</ver><qostest>false</qostest><nonce>882ffe9d-e09a-7e0c-aa63-32ca50eb93c3</nonce></connect-response>
Mar 24, 2017 10:52:18 AM fr.delthas.skype.UicConnector <clinit>
FINEST: Initializing UIC generation
Mar 24, 2017 10:52:18 AM fr.delthas.skype.UicConnector <clinit>
FINER: Overriding AES key length because of limitation
Mar 24, 2017 10:52:18 AM fr.delthas.skype.UicConnector getUIC
FINEST: Computing UIC token with username: awkaw and nonce: 882ffe9d-e09a-7e0c-aa63-32ca50eb93c3
Mar 24, 2017 10:52:18 AM fr.delthas.skype.UicConnector getUIC
FINEST: Sent UIC payload to server
Mar 24, 2017 10:52:19 AM fr.delthas.skype.UicConnector getUIC
FINEST: Computed UIC succesfully (uic length:524)
Mar 24, 2017 10:52:19 AM fr.delthas.skype.NotifConnector sendPacket
FINEST: Sent packet: ATH 2 CON\USER 568

<user><uic>AAABBAAAAAGgQjzKvUVs8ZWpk4LGSUmWtIZhZaTm/JThbsnlFQQQChbmDAekWJElnn3yfxMK5jDnSQocSxmORwNuXxanL40ycYaqnZkCKRzCBW3ODHgArHfH61OwP+38mZw0forOYWc38tPPl1vriHgKRF/rfXOkpW4gsotBTX71sxJrwmhcXAJUitLCTQgFVo1Ja2/HngyGa8hqgre0UVFbYSY7Na5LMDMDJ8MosOiu3+q9dfmPoFEPysaGXMvK1nOOGQdm9MYOYJpgyelbpHyu70Hn442Pl/52wZ2nlT4BjyB8Ga8hqgre0UVFbYSY7Na5LMDMDJ8MosOiu83Q7p6uq7D3tnSZs2YhGVCy5AybMl4rixKGJc7O9D0wUhCVNS6lYuYa9v0+/ke0sM7nuoAZ7dWHcyRCjWbugvAHMaOfHkD1kBdLK6apwEXklpJQ6EQLYr9Y/vyR4M/0HNb8ySRWFYwEkmUnFfrgWWLfA5WndjZCqRGsF+xkCZQIzBY7zJEHnREa8dEXCQIQ=</uic><id>awkaw</id></user>
Mar 24, 2017 10:52:19 AM fr.delthas.skype.NotifConnector processPacket
FINER: Received packet ATH CON
Mar 24, 2017 10:52:19 AM fr.delthas.skype.NotifConnector processPacket
FINEST: Recieved packet body: <auth-response><new-thread-allowed>false</new-thread-allowed><p2p-migration-allowed>false</p2p-migration-allowed><id>cid-(-3535921710038751101)@outlook.com</id></auth-response>
Mar 24, 2017 10:52:19 AM fr.delthas.skype.NotifConnector sendPacket
FINEST: Sent packet: BND 3 CON\MSGR 145

<msgr><ver>2</ver><client><name>.</name><ver>.</ver><networks>skype</networks></client><epid>ff3134d0-c184-b800-3b64-056dd4f8cdd9</epid></msgr>
Mar 24, 2017 10:52:19 AM fr.delthas.skype.NotifConnector readPacket
FINEST: Set registration: U2lnbmF0dXJlOjI6Mjg6QVFRQUFBQ2NxeHR2VGUweWVzM0FlUXFZYzFLZztWZXJzaW9uOjY6MToxO0lzc3VlVGltZTo0OjE5OjUyNDc5NDU0MDU4MjQ5MjU0OTk7RXAuSWRUeXBlOjc6MToxO0VwLklkOjI6Mzg6Y2lkLSgtMzUzNTkyMTcxMDAzODc1MTEwMSlAb3V0bG9vay5jb207RXAuRXBpZDo1OjM2OmZmMzEzNGQwLWMxODQtYjgwMC0zYjY0LTg6QVFRQUFBQ2NxeHR2VGUweWVzM0FlUU6NzoxOjA7RXAuQXV0aFRpbWU6NDoxOTo1MjQ3OTQ1NDA1ODIyMTEyOTY1O0VwLkF1dGhUeXBlOjc6MTo4O0VwLkV4cFRpbWU6NDoxOTo1MjQ3OTQ2MjY5ODIyMTEyOTY1O0VwLlBIX0N2ZXI6MjoxOjI7RXAuUEhfRnZlcjoyOjE6Mjs=
Mar 24, 2017 10:52:19 AM fr.delthas.skype.NotifConnector processPacket
FINER: Received packet XFR CON
Mar 24, 2017 10:52:19 AM fr.delthas.skype.NotifConnector processPacket
FINEST: Recieved packet body: <xfr><target>db5-s.gateway.messenger.live.com:443</target><flags>G</flags><state>VmVyc2lvbjogMQ0KWGZyQ291bnQ6IDENClhmclNlbnR1oXuzAubBfrerLBaDNfH1NDU2MjINCklzR2VvWGZyOiB0cnVlDQo=</state><wait>1</wait></xfr>
Mar 24, 2017 10:52:19 AM fr.delthas.skype.NotifConnector connectTo
FINEST: Connecting to hostname: db5-s.gateway.messenger.live.com port: 443
Mar 24, 2017 10:52:20 AM fr.delthas.skype.NotifConnector sendPacket
FINEST: Sent packet: CNT 1 CON 594
Registration: U2lnbmF0dXJlOjI6Mjg6QVFRQUFBQ2NxeHR2VGUweWVzM0FlUXFZYzFLZztWZXJzaW9uOjY6MToxO0lzc3VlVGltZTo0OjE5OjUyNDc5NDU0MDU4MjQ5MjU0OTk7RXAuSWRUeXBlOjc6MToxO0VwLklkOjI6Mzg6Y2lkLSgtMzUzNTkyMTcxMDAzODc1MTEwMSlAb3V0bG9vay5jb207RXAuRXBpZDo1OjM2OmZmMzEzNGQwLWMxODQtYjgwMC0zYjY0LTA1NmRkNGY4Y2RkOTtFcC5Mb2dpblRpbWU6NzoxOjA7RXAuQXV0aFRpbWU6NDoxOTo1MjQ3OTQ1NDA1ODIyMTEyOTY1O0VwLkF1dGhUeXBlOjc6MTo4O0VwLkV4cFRpbWU6NDoxOT1oXuzAubBfrerLBaDNfHOTY1O0VwLlBIX0N2ZXI6MjoxOjI7RXAuUEhfRnZlcjoyOjE6Mjs=

<connect><ver>2</ver><agent><os>.</os><osVer>.</osVer><proc>.</proc><lcid>en-us</lcid></agent></connect>
Mar 24, 2017 10:52:20 AM fr.delthas.skype.NotifConnector processPacket
FINER: Received packet CNT CON
Mar 24, 2017 10:52:20 AM fr.delthas.skype.NotifConnector processPacket
FINEST: Recieved packet body: <connect-response><ver>2</ver><qostest>false</qostest><nonce>c0bf3b08-36b6-fa2b-24a8-5a38985ad9e0</nonce></connect-response>
Mar 24, 2017 10:52:20 AM fr.delthas.skype.UicConnector getUIC
FINEST: Computing UIC token with username: awkaw and nonce: c0bf3b08-36b6-fa2b-24a8-5a38985ad9e0
Mar 24, 2017 10:52:20 AM fr.delthas.skype.UicConnector getUIC
FINEST: Sent UIC payload to server
Mar 24, 2017 10:52:20 AM fr.delthas.skype.UicConnector getUIC
FINEST: Computed UIC succesfully (uic length:524)
Mar 24, 2017 10:52:20 AM fr.delthas.skype.NotifConnector sendPacket
FINEST: Sent packet: ATH 2 CON\USER 1056
Registration: U2lnbmF0dXJlOjI6Mjg6QVFRQUFBQ2NxeHR2VGUweWVzM0FlUXFZYzFLZztWZXJzaW9uOjY6MToxO0lzc3VlVGltZTo0OjE5OjUyNDc5NDU0MDU4MjQ5MjU0OTk7RXAuSWRUeXBlOjc6MToxO0V1oXuzAubBfrerLBaDNfH1MTEwMSlAb3V0bG9vay5jb207RXAuRXBpZDo1OjM2OmZmMzEzNGQwLWMxODQtYjgwMC0zYjY0LTA1NmRkNGY4Y2RkOTtFcC5Mb2dpblRpbWU6NzoxOjA7RXAuQXV0aFRpbWU6NDoxOTo1MjQ3OTQ1NDA1ODIyMTEyOTY1O0VwLkF1dGhUeXBlOjc6MTo4O0VwLkV4cFRpbWU6NDoxOTo1MjQ3OTQ2MjY5OOjc6MToxO0V1oXuzAuBIX0N2ZXI6MjoxOjI7RXAuUEhfRnZlcjoyOjE6Mjs=

<user><uic>AAABBAAAAAGkPr+Ig5BrW5ASYQNEiAFg+rlQnKIVevaYdPxfCJ7fEB4jBY0R/JJeBCnpNHsS2EMo6Zbgrftg1zd4EBWKWmHgUMudTA9GNZi/9CeN4CtmmfzQ71oXuzAubBfrerLBaDNfHe6lClf6/MBhoiRWV73kUsKziDr3rEo5y4QoI3XuczEK2Gt2kMUNzSofhZsZOCqltwgTa+sao+WEaMwIfGUb3fHfCpUOH8eE+fypcu7p0PloE0T9POd2cbqggsoWpGDJlKKcDAQIUZfTrPHo+3PiArX1tphCNIgg1hQr9n+REXz9Mz+ui9dotlnGZY6Kxcw0VwLklkOjI6Mzg6Y2lkLSgtMzUzDO8eK7aMLGr7cJ1vBaYtw3YdypL5PHE4vGoRAbP+XfbJ5tX6ukH1et0g0GoP0O0tjRqUOrhT9C6CLGMaOL/B0+adawV/7k8Wb3AuB/QL8vKEpx0AVO5lCJb2uEnIpLMwIfGUb3fHfCpUOwYosrmMqR5B7Wn76Ljs8=</uic><id>awkaw</id></user>
Mar 24, 2017 10:52:21 AM fr.delthas.skype.NotifConnector readPacket
SEVERE: 
fr.delthas.skype.ParseException: Error message received:
911 2 CON 23

Authentication failed
	at fr.delthas.skype.NotifConnector.readPacket(NotifConnector.java:484)
	at fr.delthas.skype.NotifConnector.lambda$connect$4(NotifConnector.java:512)
	at java.lang.Thread.run(Thread.java:745)

Mar 24, 2017 10:52:21 AM fr.delthas.skype.NotifConnector lambda$connect$4
SEVERE: Error while reading packet
fr.delthas.skype.ParseException: Error message received:
911 2 CON 23

Authentication failed
	at fr.delthas.skype.NotifConnector.readPacket(NotifConnector.java:484)
	at fr.delthas.skype.NotifConnector.lambda$connect$4(NotifConnector.java:512)
	at java.lang.Thread.run(Thread.java:745)

Mar 24, 2017 10:52:21 AM fr.delthas.skype.Skype error
SEVERE: Error thrown
fr.delthas.skype.ParseException: Error message received:
911 2 CON 23

Authentication failed
	at fr.delthas.skype.NotifConnector.readPacket(NotifConnector.java:484)
	at fr.delthas.skype.NotifConnector.lambda$connect$4(NotifConnector.java:512)
	at java.lang.Thread.run(Thread.java:745)

Mar 24, 2017 10:52:21 AM fr.delthas.skype.Skype error
SEVERE: No error listener set!!!
`

Thanks)

**Comment by awkaw** [comment]
OS Linux version 3.16.0-4-amd64 (debian-kernel@lists.debian.org) (gcc version 4.8.4 (Debian 4.8.4-1) ) #1 SMP Debian 3.16.39-1 (2016-12-30)

**Comment by awkaw** [comment]
Different logins on different operating systems work differently. Login 1 can give an error in Windows, but work in Linux. Login 2 can produce an error in Linux, but work in Windows. It's strange.

**Comment by d-kar** [comment]
The fix seems to be to replace clientVersion when getting skypeToken from "0/7.12.0.101/" to "0/7.4.85.102/259/" in WebConnector.java

**Comment by AlexeenkoSN** [comment]
Hi, I have the same behaviour, but onlye for ms account (with @)
911 2 CON 23 Authentication failed. 
I've used right credentials, because win version of skype works well.
Do you have any suggestion how to solve this problem?

**Comment by metasonic** [comment]
Hey guys, did anyone manage to find a fix for this or can provide some direction on how to fix this?

**Comment by awkaw** [comment]
I started using it - https://github.com/OllieTerrance/SkPy
There is no such problem. It works quite stably.

**Comment by metasonic** [comment]
Thanks @awkaw ! Will have a look. Still want to try to fix this as it's really cool. Will see if i manage to:d

**Comment by metasonic** [comment]
@delthas  can you please provide some guidelines on how to get started with this?

**Comment by metasonic** [comment]
@haroflow did an amazing job on (#45 and #41) fabiodepin/JavaSkype@c3d3cd2. so i no longer encounter this issue when using new skype account but for some reason it still happens on my old skype account.
Attached logs bellow 
https://pastebin.com/XAhAaCYK

**Comment by fabiodepin** [comment]
The problem is with your login @outlook.com.
Please try with @hotmail.com.
Will check this.

**Comment by fabiodepin** [comment]
Hello @metasonic ,

The problem is with your login @outlook.com.
Please try with @hotmail.com.
Will check this.

**Comment by metasonic** [comment]
Hmm that's strange, I log in like Skype skype = new Skype("a.graure", "xxxxxxxxxx");|
Looking over Mirana logs rigt now and noticed the uic is a bit different Mirana logs for the same account
https://pastebin.com/pBFru4hw
@fabiodepin  any suggestion?

**Comment by metasonic** [comment]
@fabiodepin  another example of old account (non email) not working https://pastebin.com/s06Vgpz8
The 911 error appears to be linked with bad auth process, but can't put my finger on it yet

**Comment by fabiodepin** [comment]
@metasonic,

Thanks for the logs.
How can I get one user with this problem for the tests?

One option is to migrate your old account to Microsoft account.
https://blog.hqcodeshop.fi/archives/328-Removing-old-Skype-login-and-going-for-Microsoft-Account.html

I've got to sleep... 03:50 O.o

**Comment by metasonic** [comment]
You aren't able to create old skype accounts any more. Hit me up on skype I'll help you with anything you need. My id: a.graure

**Comment by haroflow** [comment]
@fabiodepin @metasonic Unfortunately, using the same code I had yesterday I couldn't log in to my skype account anymore...

Using just the username I get the 911 error message. Investigating this...
Using [username]@gmail.com it gets stuck in a loop. Solved it, checking if it's correct.

**Comment by haroflow** [comment]
@awkaw @fabiodepin We've been testing this login issues and I think we got them. Not sure if it works 100% of the time though... would need more people testing with different accounts.

https://github.com/delthas/JavaSkype/compare/master...haroflow:master

@delthas Being new to this, I'd like to ask you how to proceed. We believe this changes solves some issues listed on here, but I can't test them fully, there are a lot of cases. Should we submit pull requests to you and wait for feedback?

@metasonic Thanks for the help!

**Comment by delthas** [comment]
@haroflow Yes, sorry I haven't been very responsive to contributions over the past few months. I feel responsible for whether this library works or not, and if I wanted to do things correctly I should spend some time testing all the new changes in PRs with various accoutns and compare the library with the official Skype implementation. This is a lengthy process and I didn't really have time to do this.

So, I will now accept PRs without doing this work, so hopefully the library can move forward quickly and we can get the whole Microsoft login working. Starting with #46 .
