### ISSUE TITLE
JavaSkype w/ Spigot

### ISSUE THREAD

**Issue by ytcalifax** [Delthas/JavaSkype#52]
* **OS, Version, Architecture** *(e.g. Windows 8.1 x64)*: 
Windows 10 x64

* **JRE Vendor, Version** *(e.g. Oracle JDK 8u151)*:
Oracle JDK 8u151

### Expected behaviour
JavaSkype should initialise.

### Actual behaviour
JavaSkype does not load

### Steps to reproduce the issue
I was trying to connect via the JavaSkype client from a MineCraft Spigot plugin. However, the thing that happens is the library just dies on me because of the error below.

### Logs
```[20:04:20 ERROR]: Error occurred while enabling MinecraftCore v1.4 (Is it up to date?)
java.lang.NoClassDefFoundError: org/json/JSONException
        at fr.delthas.skype.Skype.reset(Skype.java:300) ~[?:?]
        at fr.delthas.skype.Skype.connect(Skype.java:146) ~[?:?]
        at fr.delthas.skype.Skype.connect(Skype.java:124) ~[?:?]
        at xyz.multinetwork.MCCore.onEnable(MCCore.java:34) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.13.2.jar:git-Spigot-a1ba5fe-3359cb1]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [spigot-1.13.2.jar:git-Spigot-a1ba5fe-3359cb1]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.13.2.jar:git-Spigot-a1ba5fe-3359cb1]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:431) [spigot-1.13.2.jar:git-Spigot-a1ba5fe-3359cb1]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:345) [spigot-1.13.2.jar:git-Spigot-a1ba5fe-3359cb1]
        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:584) [spigot-1.13.2.jar:git-Spigot-a1ba5fe-3359cb1]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:546) [spigot-1.13.2.jar:git-Spigot-a1ba5fe-3359cb1]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:424) [spigot-1.13.2.jar:git-Spigot-a1ba5fe-3359cb1]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [spigot-1.13.2.jar:git-Spigot-a1ba5fe-3359cb1]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:702) [spigot-1.13.2.jar:git-Spigot-a1ba5fe-3359cb1]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.ClassNotFoundException: org.json.JSONException
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:154) ~[spigot-1.13.2.jar:git-Spigot-a1ba5fe-3359cb1]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[spigot-1.13.2.jar:git-Spigot-a1ba5fe-3359cb1]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
        ... 15 more
```

**Comment by ytcalifax** [comment]
Nevermind, I had to shade everything in the JAR
