### ISSUE TITLE
java.security.InvalidKeyException: Illegal key size

### ISSUE THREAD

**Issue by MrPowerGamerBR** [Delthas/JavaSkype#9]
```
Exception in thread "Skype-Receiver-Thread" java.lang.RuntimeException: java.security.InvalidKeyException: Illegal key size
	at fr.delthas.skype.NotifConnector.processPacket(NotifConnector.java:278)
	at fr.delthas.skype.NotifConnector.lambda$2(NotifConnector.java:405)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.security.InvalidKeyException: Illegal key size
	at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1039)
	at javax.crypto.Cipher.implInit(Cipher.java:805)
	at javax.crypto.Cipher.chooseProvider(Cipher.java:864)
	at javax.crypto.Cipher.init(Cipher.java:1396)
	at javax.crypto.Cipher.init(Cipher.java:1327)
	at fr.delthas.skype.UicConnector.getUIC(UicConnector.java:221)
	at fr.delthas.skype.NotifConnector.processPacket(NotifConnector.java:276)
	... 2 more
```

**Comment by Delthas** [comment]
This is due to a stupid restriction on key lengths on Oracle JRE. I uploaded a new version that should bypass this. Please download and use the 1.0.8 version and tell me if it works.

**Comment by MrPowerGamerBR** [comment]
Will test it ASAP :)

Em 2 de ago de 2016 11:19 AM, "Delthas" <notifications@github.com> escreveu:

**Comment by MrPowerGamerBR** [comment]
@Delthas no issues on the latest build :)
